#!/usr/bin/env bash
# Configures a new Ubuntu machine by 
# installing Nginx, which should listen on port 80
# print the html file contain Hello World string

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
     sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting Nginx
sudo service nginx start

# Allowing Nginx to pass through the firewall
sudo ufw allow 'Nginx HTTP'

# Give ownership of web files to the user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Back up the default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart Nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"