#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80


echo -e "Update and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

# starting nginx
sudo service nginx start


sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creat new index  page
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '20i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '21i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/defa



# Restarting nginx
sudo service nginx restart