#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo chmod u+x /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

sudo printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    add_header X-Served-By $HOSTNAME;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
